In [1]:
import numpy as np
import scipy.ndimage.filters as spfilt
import scipy.signal as spsignal
import pynbody
import pynbody.plot as pp
import pynbody.plot.sph
import pynbody.filt as filt
import pynbody.units as units
import pynbody.analysis.profile as profile
import matplotlib.pyplot as plt
import sys, os, glob, pickle
import random as rand

rand.seed()

In [3]:
sim = pynbody.snapshot.tipsy.TipsySnap(filename='glass16.std', paramfile='./shocktube.param')
print(sim["pos"])
print(min(sim["x"]))
print(max(sim["x"]))
print(min(sim["y"]))
print(max(sim["y"]))
print(min(sim["z"]))
print(max(sim["z"]))

[[-0.24916935 -0.2029047  -0.05851364]
 [-0.1988039   0.10033798 -0.47123909]
 [ 0.48003578 -0.21688175 -0.44995308]
 ..., 
 [-0.34243774 -0.34070492 -0.16901398]
 [-0.46474838 -0.14309502  0.44415474]
 [-0.01501846  0.1952486   0.34966183]]
-0.499831199646
0.499943733215
-0.499779701233
0.499405860901
-0.499716758728
0.499901771545


/home/panueljg/anaconda3/lib/python3.5/site-packages/pynbody/snapshot/tipsy.py:130: RuntimeWarning: No readable param file in the run directory or parent directory: using defaults.
  "No readable param file in the run directory or parent directory: using defaults.", RuntimeWarning)
